Models/Vacation.cs
using System.ComponentModel.DataAnnotations;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace FinalProject.Models
{
	public class Vacation
	{
		[Key]
		public int Id { get; set; }

		[Required]
		public string Name { set; get; }

		[Required]
		[DataType(DataType.Date)]
		public DateTime Date { get; set; }


		[DataType(DataType.Date)]
		public DateTime? Created_at { get; set; } = DateTime.Now;


	}
}

Controllers/Vacation/VacationsController.cs
using FinalProject.Data;
using FinalProject.Enums;
using FinalProject.Migrations;
using FinalProject.Repository.interfaces;
using FinalProject.ViewModel;
using Microsoft.AspNetCore.Mvc;
using FinalProject.Models;
using Microsoft.AspNetCore.Authorization;
using FinalProject.Constants;

namespace FinalProject.Controllers.Vacations
{
    [Authorize]
    public class VacationsController : Controller
	{
		IVacationRepository vacationRepo;

		public VacationsController(IVacationRepository _vacationRepo)
		{

			vacationRepo = _vacationRepo;
		}



        //public IActionResult Index()
        //{
        //	var vacations = vacationRepo.GetAll();
        //	string responseData = TempData["ResponseData"] as string;
        //	if (!string.IsNullOrEmpty(responseData))
        //	{
        //		ViewData["Response"] = responseData;
        //	}

        //	return View("~/Views/Vacations/vacationTest.cshtml", vacations);
        //}


        [Authorize(Permissions.Vacations.View)]
        public IActionResult Index()
		{
			var vacations = vacationRepo.GetAll();
			string responseData = TempData["ResponseData"] as string;
			if (!string.IsNullOrEmpty(responseData))
			{
				ViewData["Response"] = responseData;
			}

			return View("~/Views/Vacations/index.cshtml", vacations);
		}

        [Authorize(Permissions.Vacations.Create)]
        public IActionResult Create(VacationViewModel vacationViewModel)
		{

			if (ModelState.IsValid)
			{
				Vacation vacation = new Vacation()
				{ Name = vacationViewModel.Name, Date = vacationViewModel.Date, Created_at = vacationViewModel.Created_at };
				vacationRepo.Insert(vacation);
				vacationRepo.SaveChanges(); // Save changes to the database
				TempData["ResponseData"] = Responses.success.ToString();
			}
			else
			{
				TempData["ResponseData"] = Responses.fail.ToString();
			}

			return RedirectToAction("Index");
		}




        //[HttpPost]
        //public IActionResult Create(VacationViewModel vacationViewModel)
        //{
        //    try
        //    {
        //        if (ModelState.IsValid == true)
        //        {
        //            Vacation vacation = new Vacation()
        //            { Name = vacationViewModel.Name, Date = vacationViewModel.Date, Created_at = vacationViewModel.Created_at };
        //            vacationRepo.Insert(vacation);
        //            vacationRepo.SaveChanges(); // Save changes to the database
        //            TempData["ResponseData"] = Responses.success.ToString();
        //            return RedirectToAction("Index");
        //        }
        //        else
        //        {
        //            TempData["ResponseData"] = Responses.fail.ToString();
        //            return View(vacationViewModel);
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        TempData["ResponseData"] = Responses.fail.ToString();
        //        return RedirectToAction("Index");
        //    }
        //}


        [Authorize(Permissions.Vacations.Delete)]
        public IActionResult Delete(int id)
		{
			try
			{
				Vacation vacation = vacationRepo.GetById(id);
				vacationRepo.Delete(vacation);
				vacationRepo.SaveChanges();
				TempData["ResponseData"] = Responses.success.ToString();
			}catch (Exception ex)
			{
				TempData["ResponseData"] = Responses.fail.ToString();
			}

			return RedirectToAction("Index");
		}


        public IActionResult Edit()
		{
			return View();
		}





	}
}

Controllers/Vacation/VacationtestController.cs
using FinalProject.Models;
using FinalProject.Repository.interfaces;
using Humanizer;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.DotNet.Scaffolding.Shared.CodeModifier.CodeChange;
using Microsoft.EntityFrameworkCore;
using System.Buffers.Text;
using System.Drawing.Printing;
using FinalProject.Models;
using FinalProject.Enums;
using FinalProject.ViewModel;

namespace FinalProject.Controllers.Vacations
{

    public class VacationtestController : Controller
    {
        IVacationRepository vacationRepo;

        public VacationtestController(IVacationRepository _vacationRepo)
        {

            vacationRepo = _vacationRepo;
        }

        public IActionResult Index(int page = 1, int pageSize = 3 ,bool HasPrevicePage=true , bool HasNextPage = true)
        {
            var vacations = vacationRepo.GetAll()
                .OrderByDescending(v => v.Date)
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();

            var totalRecords = vacationRepo.GetAll().Count();
            var totalPages = (int)Math.Ceiling((double)totalRecords / pageSize);

            var model = new PaginatedList<Vacation>(vacations, page, pageSize, totalRecords, totalPages,  HasPrevicePage , HasNextPage);

           

            string responseData = TempData["ResponseData"] as string;
            if (!string.IsNullOrEmpty(responseData))
            {
                ViewData["Response"] = responseData;
            }

            return View(model);
        }


		public IActionResult Create(VacationViewModel vacationViewModel)
		{

			if (ModelState.IsValid)
			{
				Vacation vacation = new Vacation()
				{ Name = vacationViewModel.Name, Date = vacationViewModel.Date, Created_at = vacationViewModel.Created_at };
				vacationRepo.Insert(vacation);
				vacationRepo.SaveChanges(); // Save changes to the database
				TempData["ResponseData"] = Responses.success.ToString();
			}
			else
			{
				TempData["ResponseData"] = Responses.fail.ToString();
			}

			return RedirectToAction("Index");
		}




		public IActionResult Delete(int id)
		{
			try
			{
				Vacation vacation = vacationRepo.GetById(id);
				vacationRepo.Delete(vacation);
				vacationRepo.SaveChanges();
				TempData["ResponseData"] = Responses.success.ToString();
			}
			catch (Exception ex)
			{
				TempData["ResponseData"] = Responses.fail.ToString();
			}

			return RedirectToAction("Index");
		}




	}



}

Views/Vacations/Index.cshtml
@model List<Vacation>

@{
	ViewData["Title"] = "Official Holidays";
	ViewData["ActiveLink"] = "vacations";
}

<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
	<!--begin::Post-->
	<div class="post d-flex flex-column-fluid" id="kt_post">
		<!--begin::Container-->
		<div id="kt_content_container" class="container-xxl">
			<!--begin::Card-->
			<div class="card">
				<!--begin::Card header-->
				<div class="card-header border-0 pt-6">
					<!--begin::Card title-->
					<div class="card-title">
						<!--begin::Search-->
						<div class="d-flex align-items-center position-relative my-1">
							<!--begin::Svg Icon | path: icons/duotune/general/gen021.svg-->
							<span class="svg-icon svg-icon-1 position-absolute ms-6">
								<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
									<rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="black"></rect>
									<path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="black"></path>
								</svg>
							</span>
							<!--end::Svg Icon-->
							<input type="text" data-kt-customer-table-filter="search" class="form-control form-control-solid w-250px ps-15" placeholder="Search Vacations">
						</div>
						<!--end::Search-->
					</div>
					<!--begin::Card title-->
					<!--begin::Card toolbar-->
					<div class="card-toolbar">
						<!--begin::Toolbar-->
						<div class="d-flex justify-content-end" data-kt-customer-table-toolbar="base">
							
							<!--begin::Add customer-->
							@*<a asp-controller="Exam" asp-action="Create" type="button" class="btn btn-primary">
								New Vacation
							</a>*@
							<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#kt_modal_add_customer">Add New Vacation</button>
							<!--end::Add customer-->
						</div>
						<!--end::Toolbar-->
						<!--begin::Group actions-->
						<div class="d-flex justify-content-end align-items-center d-none" data-kt-customer-table-toolbar="selected">
							<div class="fw-bolder me-5">
								<span class="me-2" data-kt-customer-table-select="selected_count"></span>Selected
							</div>
							<button type="button" class="btn btn-danger" data-kt-customer-table-select="delete_selected">Delete Selected</button>
						</div>
						<!--end::Group actions-->
					</div>
					<!--end::Card toolbar-->
				</div>
				<!--end::Card header-->
				<!--begin::Card body-->
				<div class="card-body pt-0">
					<!--begin::Table-->
					<div id="kt_customers_table_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
						<div class="table-responsive">
							<table class="table align-middle table-row-dashed fs-6 gy-5 dataTable no-footer" id="kt_customers_table">
								<!--begin::Table head-->
								<thead>
									<!--begin::Table row-->
									<tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">

										<th class="min-w-125px sorting" tabindex="0" aria-controls="kt_customers_table" rowspan="1" colspan="1" aria-label="Customer Name: activate to sort column ascending" style="width: 146.1px;">Vacation Name</th>
										<th class="min-w-125px sorting" tabindex="0" aria-controls="kt_customers_table" rowspan="1" colspan="1" aria-label="Email: activate to sort column ascending" style="width: 191.4px;">Date</th>

										<th class="min-w-125px sorting" tabindex="0" aria-controls="kt_customers_table" rowspan="1" colspan="1" aria-label="Created Date: activate to sort column ascending" style="width: 152.637px;">Created Date</th>
										<th class="text-end min-w-70px sorting_disabled" rowspan="1" colspan="1" aria-label="Actions" style="width: 111.512px;">Actions</th>
									</tr>
									<!--end::Table row-->
								</thead>
								<!--end::Table head-->
								<!--begin::Table body-->
								<tbody class="fw-bold text-gray-600">
									@foreach (var vacation in Model)
									{
										<tr class="odd">

											<!--begin::Name=-->
											<td>
												@vacation.Name
											</td>
											<!--end::Name=-->
											<!--begin::vacation  Date=-->
											<td data-order="2020-12-14T20:43:00+02:00">@vacation.Date</td>
											<!--end::vacation Date=-->
											<!--begin::created at=-->
											<td data-order="2020-12-14T20:43:00+02:00">@vacation.Created_at</td>
											<!--end::created at=-->
											<!--begin::Action=-->
											<td class="text-end">
												<a href="#" class="btn btn-sm btn-light btn-active-light-primary" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">
													Actions
													<!--begin::Svg Icon | path: icons/duotune/arrows/arr072.svg-->
													<span class="svg-icon svg-icon-5 m-0">
														<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
															<path d="M11.4343 12.7344L7.25 8.55005C6.83579 8.13583 6.16421 8.13584 5.75 8.55005C5.33579 8.96426 5.33579 9.63583 5.75 10.05L11.2929 15.5929C11.6834 15.9835 12.3166 15.9835 12.7071 15.5929L18.25 10.05C18.6642 9.63584 18.6642 8.96426 18.25 8.55005C17.8358 8.13584 17.1642 8.13584 16.75 8.55005L12.5657 12.7344C12.2533 13.0468 11.7467 13.0468 11.4343 12.7344Z" fill="black"></path>
														</svg>
													</span>
													<!--end::Svg Icon-->
												</a>
												<!--begin::Menu-->
												<div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-bold fs-7 w-125px py-4" data-kt-menu="true">
													@*	<!--begin::Menu item-->
												<div class="menu-item px-3">
												<a href="../../demo8/dist/apps/customers/view.html" class="menu-link px-3">Edit</a>
												</div>
												<!--end::Menu item-->*@

													<!--begin::Menu item-->
													@*<div class="menu-item px-3">
														<a asp-action="Delete" asp-controller="Vacations" asp-route-id="@vacation.Id" class="menu-link px-3" data-kt-customer-table-filter="delete_row">Delete</a>
													</div>*@
													<div class="delete_project_btn menu-item px-3" data-kt-customer-table-filter="delete_row" data-bs-toggle="modal" data-bs-target="#kt_modal_new_card">
														<a href="" onclick="confirmDelete('@vacation.Id')" class="menu-link px-3" data-kt-customer-table-filter="delete_row" data-bs-toggle="modal" data-bs-target="#kt_modal_new_card">Delete</a>
													</div>
	                                            <!--end::Menu item-->

												</div>
												<!--end::Menu-->
											</td>
											<!--end::Action=-->
										</tr>
									}
								</tbody>
								<!--end::Table body-->
							</table>
							</div>
					<!--end::Table-->
				</div>
				<!--end::Card body-->
			</div>
			<!--end::Card-->



			<!--begin::Modals-->
			<!--begin::Modal - Customers - Add-->
			<div class="modal fade" id="kt_modal_add_customer" tabindex="-1" style="display: none;" aria-hidden="true">
				<!--begin::Modal dialog-->
				<div class="modal-dialog modal-dialog-centered mw-650px">
					<!--begin::Modal content-->
					<div class="modal-content">
						@*	<!--begin::Form--    action="#">*@
						<form class="form fv-plugins-bootstrap5 fv-plugins-framework" asp-action="create" asp-controller="Vacations" id="kt_modal_add_customer_form" data-kt-redirect="../../demo8/dist/apps/customers/list.html">
							<!--begin::Modal header-->
							<div class="modal-header" id="kt_modal_add_customer_header">
								<!--begin::Modal title-->
								<h2 class="fw-bolder">Add New Vacation</h2>
								<!--end::Modal title-->
								<!--begin::Close-->
								<div id="kt_modal_add_customer_close" class="btn btn-icon btn-sm btn-active-icon-primary">
									<!--begin::Svg Icon | path: icons/duotune/arrows/arr061.svg-->
									<span class="svg-icon svg-icon-1">
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
											<rect opacity="0.5" x="6" y="17.3137" width="16" height="2" rx="1" transform="rotate(-45 6 17.3137)" fill="black"></rect>
											<rect x="7.41422" y="6" width="16" height="2" rx="1" transform="rotate(45 7.41422 6)" fill="black"></rect>
										</svg>
									</span>
									<!--end::Svg Icon-->
								</div>
								<!--end::Close-->
							</div>
							<!--end::Modal header-->
							<!--begin::Modal body-->
							<div class="modal-body py-10 px-lg-17">
								<!--begin::Scroll-->
								<div class="scroll-y me-n7 pe-7" id="kt_modal_add_customer_scroll" data-kt-scroll="true" data-kt-scroll-activate="{default: false, lg: true}" data-kt-scroll-max-height="auto" data-kt-scroll-dependencies="#kt_modal_add_customer_header" data-kt-scroll-wrappers="#kt_modal_add_customer_scroll" data-kt-scroll-offset="300px" style="">
									<!--begin::Input group-->
									<div class="fv-row mb-7 fv-plugins-icon-container">
										<!--begin::Label-->
										<label class="required fs-6 fw-bold mb-2"> Vacation Name</label>
										<!--end::Label-->
										<!--begin::Input-->
										<input type="text" class="form-control form-control-solid" placeholder="" name="name" value="">
										<!--end::Input-->

										<div class="fv-plugins-message-container invalid-feedback"></div>
									</div>
									<!--end::Input group-->
									<!--begin::Input group-->
									<div class="fv-row mb-7 fv-plugins-icon-container">
										<!--begin::Label-->
										<label class="fs-6 fw-bold mb-2">
											<span class="required">Date</span>
										</label>
										<!--end::Label-->
										<!--begin::Input-->
											<input class="form-control custom_date_picker" placeholder="Pick a date" name="Date" />
										@*<input type="email" class="form-control form-control-solid" placeholder="" name="email" value="sean@dellito.com">*@
										<!--end::Input-->
										<div class="fv-plugins-message-container invalid-feedback"></div>
									</div>
									<!--end::Input group-->
								
							</div>
							<!--end::Modal body-->
							<!--begin::Modal footer-->
							<div class="modal-footer flex-center">
								<!--begin::Button-->
								<button type="reset" id="kt_modal_add_customer_cancel" class="btn btn-light me-3">Discard</button>
								<!--end::Button-->
								<!--begin::Button-->
								<button type="submit" id="kt_modal_add_customer_submit" class="btn btn-primary">
									<span class="indicator-label">Submit</span>
									<span class="indicator-progress">
										Please wait...
										<span class="spinner-border spinner-border-sm align-middle ms-2"></span>
									</span>
								</button>
								<!--end::Button-->
							</div>
							<!--end::Modal footer-->
							<div></div>
						</form>
						<!--end::Form-->
					</div>
						

					</div>
			</div>
			<!--end::Modal - Customers - Add-->
		</div>
		<!--end::Container-->
		
		</div>
	</div>



		</div>
		<!--end::Post-->
	</div>


		
@section JS{
	<script>
	// Function to show SweetAlert confirmation
	function confirmDelete(id) {
		Swal.fire({
			title: 'Are you sure?',
			text: 'You are about to delete this Message. This action cannot be undone.',
			icon: 'warning',
			showCancelButton: true,
			confirmButtonColor: '#3085d6',
			cancelButtonColor: '#d33',
			confirmButtonText: 'Yes, delete it!'
		}).then((result) => {
			if (result.isConfirmed) {
				// If confirmed, redirect to the delete action
				window.location.href = '/vacations/Delete/'+id;
			}
		});
	}

</script>

}